monolog:
  channels: ["request"]
  handlers:
    request_logs:
      type: stream
      path: "%kernel.logs_dir%/request.log"
      level: info
      channels: ["request"] # Utilisation du canal 'request'
